name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main # Change this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16 # Use the Node.js version that matches your project

    - name: Install dependencies
      run: npm ci # Replace with 'yarn install' if you're using yarn

    - name: Build project
      run: npm run build # Replace with 'yarn build' if you're using yarn

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: internshipdbdb
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./
